---
resources:
- name: my-local-repo
  type: git
  source:
    uri: https://github.com/spareslant/concourse-experiments.git
    branch: master

jobs:
- name: two-tasks-in-a-job
  plan:
    - task: hello-world
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello world"]
    - task: hello-earth
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello earth"]

- name: second-job-in-same-pipeline
  plan:
    - task: hello-universe
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello universe"]

- name: a-task-defined-in-other-file
  plan:
    - get: my-local-repo
    - task: refctored-task
      file: my-local-repo/tasks/task_hello_world.yml

- name: a-task-consuming-a-resource
  plan:
    - get: my-local-repo
    - task: refctored-task
      file: my-local-repo/tasks/task_uname.yml

- name: producer-and-consumer-tasks-in-a-job
  plan:
    - get: my-local-repo
    - task: use-repo-produce-output
      file: my-local-repo/tasks/produce_output.yml
    - task: show-output-from-previous-task
      file: my-local-repo/tasks/show_output.yml
      
