---
resources:
- name: my-local-repo
  type: git
  source:
    uri: ssh://git@192.168.0.19:10022/gpal/concourse-experiments.git
    branch: master
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      DUMMY CHARACTERS FOR PRIVATE KEYS
      -----END OPENSSH PRIVATE KEY-----

jobs:
- name: first-job
  plan:
    - task: hello-world
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello world"]
    - task: hello-earth
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello earth"]

- name: second-job
  plan:
    - task: hello-universe
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: ["hello universe"]

- name: third-job
  plan:
    - get: my-local-repo
    - task: refctored-task
      file: my-local-repo/tasks/task-hello-world.yml
